blog/urls.py
from django.urls import path
from .import views

app_name='blog'
urlpatterns = [
    path('feed/', views.post_list, name='post_list' ),
    path('auto_search/', views.auto_search, name='auto_search'),
    path('like', views.like_post, name='like_post'),
    path('follow', views.follow, name='follow'),
    path('<int:id>/post-edit', views.post_edit, name='post_edit'),
    path('<int:id>/post-delete', views.post_delete, name="post_delete"),
    path('<int:id>/', views.post_detail, name='post_detail'),
    path('<int:post_id>/comment-delete/<int:id>', views.comment_delete, name="comment_delete"),
    path('<int:reply_id>/reply-delete/<int:post_id>/<int:comment_id>', views.reply_delete, name="reply_delete"),
    path('create-post/', views.post_create, name='create_post'),
    path('login/', views.user_login , name="user_login"),
    path('logout/', views.user_logout , name="user_logout"),
    path('registration/', views.user_registration, name="user_registration"),
    path('edit-profiles/', views.edit_profile, name='edit_profile'),
    path('profile/<str:username>/<int:id>/', views.profile, name='profile'),
    path('cover-photo/', views.photo_list , name="photo_list"),
    path('avatar/', views.avatar_list , name="avatar"),
    path('profile/<str:username>.<int:id>/<int:photo_id>', views.coverUpdate, name="coverUpdate"),
    path('coverRemove/<str:username>.<int:id>', views.coverRemove, name="coverRemove"),
    path('coverDelete/<int:id>/', views.coverDelete, name="coverDelete"),
    path('profile/<str:username>/<int:id>', views.avatarUpdate, name="avatarUpdate"),
    path('avatarRemove/<str:username>/<int:id>', views.avatarRemove, name="avatarRemove"),
    path('avatarDelete/<int:id>', views.avatarDelete, name="avatarDelete"),
    path('settings/<str:username>/', views.settings, name="settings"),
    path('delete/', views.delete_profile, name="delete_profile"),
    path('gallery/<str:username>/', views.gallery, name="galley"),
    path('password_change/', views.change_password, name='change_password'),
    
] 

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static





app_name={'blog','filetype'}
urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('blog.urls', namespace='blog')),
    
    

    # password reset urls
	path('password-reset/', 
		auth_views.PasswordResetView.as_view(template_name='account/password_reset_form.html',email_template_name = 'account/password_reset_email.html'), 
		name="password_reset"),
	path('password-reset/done/', 
		auth_views.PasswordResetDoneView.as_view(template_name='account/password_reset_done.html'), 
		name="password_reset_done"),
	path('password-reset/confirm/<uidb64>/<token>', 
		auth_views.PasswordResetConfirmView.as_view(template_name='account/password_reset_confirm.html',), 
		name="password_reset_confirm"),
	path('password-reset/complete/', 
		auth_views.PasswordResetCompleteView.as_view(template_name='account/password_reset_complete.html'), 
		name="password_reset_complete")
]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from django.db.models.signals import pre_save
from django.dispatch import receiver
import filetype
from django.conf import settings
from blog.fileChecker import File_type


class Post(models.Model):
	author = models.ForeignKey(User, related_name='blog_posts', on_delete=models.CASCADE)
	body = models.TextField(null=True, blank=True)
	media = models.FileField(upload_to='post_pics', null=True, blank=True)
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)
	likes = models.ManyToManyField(User, related_name='likes', blank=True)
	user_tagged = models.ManyToManyField(User, related_name="user_tagged", null=True, blank=True)
	
	def __str__(self):
		return '{} - {} - {}'.format(str(self.author.username), self.body[:20], str(self.created))

	def total_likes(self):
		return self.likes.count()

	def get_absolute_url(self):
		return reverse('blog:post_detail', args=[self.id,])

	def media_kind(self):
		if settings.DEBUG:
			media_path = settings.BASE_DIR + self.media.url
		else:
			media_path = self.media.url
		
		kind = filetype.guess(media_path)
		
		if kind.mime in File_type.image_type():
			return "image"
		elif kind.mime in File_type.video_type():
			return "video"
		else:
			return "Media type not supported"


class Profile(models.Model):
	user = models.OneToOneField(User, on_delete = models.CASCADE)
	birthday = models.DateField(null=True, blank=True)
	avatar = models.ImageField(default='default/avatar_default.jpg', upload_to='profile_pics', null=True, blank=True)
	cover_image = models.ImageField(default='default/defalt_cover.jpg', upload_to='bg_image', null=True, blank=True)
	follow = models.ManyToManyField(User, related_name='following', blank=True)
	country = models.CharField(max_length=100, blank=True, null=True)
	current_City =  models.CharField(max_length=100, blank=True, null=True)
	about_Myself = models.CharField(max_length=200, blank=True, null=True)
	profession = models.CharField(max_length=200, blank=True, null=True)

	def profile_url(self):
		return reverse('blog:profile', args=[self.user.username, self.user.id])

	def total_followers(self):
		return self.follow.count()
	
	def total_following(self):
		return self.user.following.count()

	def __str__(self):
		return self.user.username

	def get_absolute_url(self):
		return reverse('blog:profile', args=[self.user.username, self.user.id])


class Photo(models.Model):
	profile_user = models.ForeignKey(User, on_delete = models.CASCADE)
	file = models.ImageField(upload_to='bg_image', null=True, blank=True)
	uploaded_at = models.DateTimeField(auto_now_add=True)

	class Meta:
		verbose_name = 'photo'
		verbose_name_plural = 'photos'

	def __str__(self):
		return self.profile_user.username


class AvatarPhoto(models.Model):
	avatar_user = models.ForeignKey(User, on_delete = models.CASCADE)
	file = models.ImageField(upload_to='profile_pics', null=True, blank=True)

	class Meta:
		verbose_name = 'avatarPhoto'
		verbose_name_plural = 'avatarPhotos'

	def __str__(self):
		return self.avatar_user.username


class Comment(models.Model):
	post = models.ForeignKey(Post, on_delete = models.CASCADE )
	user = models.ForeignKey(User, on_delete = models.CASCADE)
	reply = models.ForeignKey('self', on_delete=models.CASCADE, null=True, related_name='replies')
	content = models.TextField(max_length=100)
	timestamp = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return '{}-{}'.format(self.content[:20], str(self.user.username))


class Notification(models.Model):
	receiver_user = models.ForeignKey(User, on_delete = models.CASCADE)
	message = models.TextField(max_length=100)
	timestamp = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return self.message




blog/forms.py
from django import forms
from .models import Post, User, Profile, Comment, Photo, AvatarPhoto
from django.core.exceptions import ValidationError
from django.contrib.auth.forms import UserCreationForm
from PIL import Image
from django.core.files import File
from blog.fileChecker import file_size

class PostCreationForm(forms.ModelForm):	
	body = forms.CharField(label="Content", widget=forms.Textarea(attrs={'class': 'form-control border-info ', 'rows':5, 'placeholder':'Write Something Here...'}))
	media = forms.FileField(label="media", widget=forms.ClearableFileInput(attrs={'class': 'media-form','accept': {'image/*', 'video/*'}}),required=False, validators=[file_size])

	class Meta():
		model = Post
		fields= ('body', 'media') 



class PostEditForm(forms.ModelForm):
	body = forms.CharField(label="Content", widget=forms.Textarea(attrs={'class': 'form-control', 'rows':3}), required=False)
	
	class Meta():
		model = Post
		fields= ('body', 'media')


class UserLoginForm(forms.Form):
	username= forms.CharField(label="Username",max_length=20, widget=forms.TextInput(attrs={'class': 'form-control'}))
	password = forms.CharField(label="Password", max_length=100, min_length=8, widget=forms.PasswordInput(attrs={'class': 'form-control'}))


class UserRegistrationForm(UserCreationForm):
	first_name = forms.CharField(max_length=15, widget=forms.TextInput(attrs={'class': 'form-control form-control', 'placeholder':'Fist Name'}))
	last_name = forms.CharField(max_length=15, widget=forms.TextInput(attrs={'class': 'form-control form-control','placeholder':'Last Name'}))
	username = forms.CharField(label="Username",max_length=15, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder':'Username'}))
	email = forms.EmailField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder':'Email'}))
	password1 = forms.CharField(label="Password", max_length=100, min_length=8, widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder':'Password'}))
	password2 = forms.CharField(label="Confirm Password", max_length=100, min_length=8, widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder':'Confirm Password'}))

	def clean_username(self):
		username = self.cleaned_data['username']
		qs = User.objects.filter(username=username.lower())
		if qs.exists():
			raise ValidationError('Username is already taken.')
		elif len(qs)>15:
			raise ValidationError("Number of characters can't be more than 15.")
		else:
			return username
		

	def clean_email(self):
		email = self.cleaned_data['email']
		qs = User.objects.filter(email=email)
		if qs.exists():
			raise ValidationError('Email is already registered.')
		else: 
			return email
		

	def clean(self):
		cleaned_data = super().clean()
		p1 = cleaned_data.get('password1')
		p2 = cleaned_data.get('password2')
		if p1 and p2:
			if p1 != p2:
				raise ValidationError('Passwords do not match')
		
class UserEditForm(forms.ModelForm):
	username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control form-control-sm','readonly':'readonly'}))
	email = forms.EmailField(widget=forms.TextInput(attrs={'class': 'form-control form-control-sm'}))
	first_name = forms.CharField(max_length=15, widget=forms.TextInput(attrs={'class': 'form-control form-control-sm'}))
	last_name = forms.CharField(max_length=15, widget=forms.TextInput(attrs={'class': 'form-control form-control-sm'}))
	class Meta:
		model = User
		fields = {
			'username', 'email', 'first_name', 'last_name',
		}	

class ProfileEditForm(forms.ModelForm):
	birthday = forms.DateField(widget=forms.DateInput(attrs={'class':'form-control form-control-sm'}))
	country = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'form-control form-control-sm'}), required=False)
	current_City = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'form-control form-control-sm'}), required=False)
	about_Myself = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'form-control form-control-sm'}), required=False)
	profession = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'form-control form-control-sm'}), required=False)
	class Meta:
		model = Profile
		exclude = ['user', 'follow', 'avatar', 'cover_image']

		

class UserCommentForm(forms.ModelForm):
	content = forms.CharField(label="", widget=forms.Textarea(attrs={'class': 'form-control border border-info', 'rows':1,}))

	class Meta:
		model = Comment
		fields = {'content',}
		

class PhotoForm(forms.ModelForm):
	
	x = forms.FloatField(widget=forms.HiddenInput())
	y = forms.FloatField(widget=forms.HiddenInput())
	width = forms.FloatField(widget=forms.HiddenInput())
	height = forms.FloatField(widget=forms.HiddenInput())

	class Meta:
		model = Photo
		fields = ('file', 'x', 'y', 'width', 'height')
		widgets = {
			'file': forms.FileInput(attrs = {
				'accept': 'image/*'  # this is not an actual validation! don't rely on that!
			})
		}


	def save(self):
		photo = super(PhotoForm, self).save()
		
		x = self.cleaned_data.get('x')
		y = self.cleaned_data.get('y')
		w = self.cleaned_data.get('width')
		h = self.cleaned_data.get('height')

		image = Image.open(photo.file)
		cropped_image = image.crop((x, y, w+x, h+y))
		resized_image = cropped_image.resize((1600, 300), Image.ANTIALIAS)
		resized_image.save(photo.file.path)

		return photo


class AvatarPhotoForm(forms.ModelForm):
	
	x = forms.FloatField(widget=forms.HiddenInput())
	y = forms.FloatField(widget=forms.HiddenInput())
	width = forms.FloatField(widget=forms.HiddenInput())
	height = forms.FloatField(widget=forms.HiddenInput())

	class Meta:
		model = AvatarPhoto
		fields = ('file', 'x', 'y', 'width', 'height')
		widgets = {
			'file': forms.FileInput(attrs = {
				'accept': 'image/*'  # this is not an actual validation! don't rely on that!
			})
		}


	def save(self):
		avatarPhoto = super(AvatarPhotoForm, self).save()
		
		x = self.cleaned_data.get('x')
		y = self.cleaned_data.get('y')
		w = self.cleaned_data.get('width')
		h = self.cleaned_data.get('height')

		image = Image.open(avatarPhoto.file)
		cropped_image = image.crop((x, y, w+x, h+y))
		resized_image = cropped_image.resize((200, 200), Image.ANTIALIAS)
		resized_image.save(avatarPhoto.file.path)

		return avatarPhoto

templates/blog/base.html
<!DOCTYPE html>
{% load static %}

<html>
<head>
	<title>
		{% block title %}
		{% endblock %}
	</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
	<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
	<link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/themes/smoothness/jquery-ui.css">


	<link rel='stylesheet' type='text/css' href="{% static 'blog/style.css' %}">
	{% block head_extra %}
	{% endblock %}
	<script
      defer
      src="https://use.fontawesome.com/releases/v5.0.8/js/all.js"
      integrity="sha384-SlE991lGASHoBfWbelyBPLsUlwY1GwNDJo3jSJO04KZ33K2bwfV9YBauFfnzvynJ"
      crossorigin="anonymous">
    </script>
    <style type="text/css">
    	body {
			background-color: #e3e8e5;
    	}
        .ui-autocomplete {
        	z-index: 99999
        }
    </style>
<body>
	{% include 'blog/navbar.html' %}
	
	<div class="content" style="padding-top: 60px;">
	{% block content %}
	{% endblock %}
	</div>


	
	<!--Bootstarp script-->
	<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
	
	


	<!--jquerui script-->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
	<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  	<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>	
  	

  	<style type="text/css">
  		.ui-autocomplete{
  			border-radius:5px;
  			position: fixed; 
  		}
		.ui-autocomplete li a{
			display: block;
		}
		.ui-datepicker { font-size:9pt !important}
  		
  	</style>
  		
  	
	<script type="text/javascript">

		$(document).ready(function(event){
			$('#delete').click(function(){
				return confirm("Are you sure to delete this post?");
			})

			$('.reply-btn').click(function(){
				$(this).parent().parent().next('.replied-comments').fadeToggle()
			});

			/* like */
			$(document).on('click', '#like', function(event){
				event.preventDefault();
				var pk = $(this).attr('value');
				$.ajax({
					type: 'POST',
					url: '{% url "blog:like_post" %}',
					data: {'id':pk, 'csrfmiddlewaretoken': '{{ csrf_token }}'},
					dataType: 'json',
					success: function(response){
						$('#like-section'+pk).html(response['form'])
						console.log($('#like-section'+pk).html(response['form']));
					},
					error: function(rs, e){
						console.log(rs.responseText);
					},
				});
			});

			/* Follow */
			$(document).on('click', '#follow', function(event){
				event.preventDefault();
				var pk = $(this).attr('value');
				$.ajax({
					type: 'POST',
					url: '{% url "blog:follow" %}',
					data: {'id':pk, 'csrfmiddlewaretoken': '{{ csrf_token }}'},
					dataType: 'json',
					success: function(response){
						$('#follow-section').html(response['form'])
						console.log($('#follow-section').html(response['form']));
					},
					error: function(rs, e){
						console.log(rs.responseText);
					},
				});
			});

			/* Autocomplete*/
			$( function() {
			    $( "#profile" ).autocomplete({
			    	
			      source: '{% url "blog:auto_search" %}',
			      position: { my : "right top", at: "right bottom", },
			   	
			      select: function( event, ui ) {
			        $( "#profile" ).attr( "src", "images/" + ui.item.img );
			        $( "#profile" ).val( ui.item.value );
			        $( "#profile" ).attr("href", "url/" + ui.item.url );
			        return false;
			      }

			    })
			    .autocomplete( "instance" )._renderItem = function( ul, item ) {
			      return $( "<li>" )
			        .append("<a href="+item.url+" style='text-decoration:none; border-radius:2px; border:none; padding-left:2px; padding-right: 2px;'><img src='"+item.image+"'height='30' style='border-radius:25px' /> <small>" +"@" + item.label +  " </small></a>")
			        .appendTo( ul );
			    };
			    });  
		});

			/* comment form */
			$(document).on('submit', '.comment-form', function(event){
				event.preventDefault();
				console.log($(this).serialize());
				$.ajax({
					type: 'POST',
					url: $(this).attr('action'),
					data: $(this).serialize(),
					dataType: 'json',
					success: function(response){
						$('.main-form').html(response['form']);
						$('textarea').val('');
						$('.reply-btn').click(function(){
						$(this).parent().parent().next('.replied-comments').fadeToggle()
					});
					},
					error: function(rs, e){
						console.log(rs.responseText);
					},
				});
			});
			/* reply form */
			$(document).on('submit', '.reply-form', function(event){
				event.preventDefault();
				console.log($(this).serialize());
				$.ajax({
					type: 'POST',
					url: $(this).attr('action'),
					data: $(this).serialize(),
					dataType: 'json',
					success: function(response){
						$('.main-form').html(response['form']);
						$('textarea').val('');
						$('.reply-btn').click(function(){
						$(this).parent().parent().next('.replied-comments').fadeToggle()
					});
					},
					error: function(rs, e){
						console.log(rs.responseText);
					},
				});
			});

			$(document).ready(function(){
			  $(".about").click(function(){
			    $("#about").toggle();
			  });
			});

			$(document).ready(function(){
				$( "#id_birthday" ).datepicker({
			      changeMonth: true,
			      changeYear: true,
			      yearRange: '1900:c',
			      minDate: new Date(1900, 1-1, 1),
			      maxDate: '-13Y',
			    });
			  } );

			$( function() {
			    $( "#tabs" ).tabs();
			  } );

			$("form").submit(function() {
			  if (window.File && window.FileReader && window.FileList && window.Blob) {
			    var file = $('#id_media')[0].files[0];

			    if (file && file.size > 5 * 1024 * 1024) {
			      alert("File " + file.name + " has a size greater than 5 MB. Please upload files less than 5 MB. ");
			      return false;
			    }
			  }
			});

			//lazy-loading
			document.addEventListener("DOMContentLoaded", function() {
			  var lazyloadImages = document.querySelectorAll("img.lazy");    
			  var lazyloadThrottleTimeout;
			  
			  function lazyload () {
			    if(lazyloadThrottleTimeout) {
			      clearTimeout(lazyloadThrottleTimeout);
			    }    
			    
			    lazyloadThrottleTimeout = setTimeout(function() {
			        var scrollTop = window.pageYOffset;
			        lazyloadImages.forEach(function(img) {
			            if(img.offsetTop < (window.innerHeight + scrollTop)) {
			              img.src = img.dataset.src;
			              img.classList.remove('lazy');
			            }
			        });
			        if(lazyloadImages.length == 0) { 
			          document.removeEventListener("scroll", lazyload);
			          window.removeEventListener("resize", lazyload);
			          window.removeEventListener("orientationChange", lazyload);
			        }
			    }, 20);
			  }
			  
			  document.addEventListener("scroll", lazyload);
			  window.addEventListener("resize", lazyload);
			  window.addEventListener("orientationChange", lazyload);
			});
	</script>
</body>
</html>

templates/blog/follow.html
{% load static %}

<div class="follow-container" style="text-align: center;">
<div class="follow-detail mb-1">
	<a class="border border-info p-2" style="color: grey;margin:5px; border-radius: 20px; ">{{ total_following }} Following</a>
	<a class="border border-info p-2" style="color: grey;margin:5px; border-radius: 20px; ">{{ total_followers }} Follower{{ total_followers|pluralize }}</a>
</div>

{% if request.user.id != profile.user.id %}
	<form action="{% url 'blog:follow' %}" method="post">
		{% csrf_token %}
		
		{% if is_followed %}
		<a type="submit" id="follow" name="profile_id" value="{{ profile.id }}" class="btn btn-light m-2"><i class="fas fa-thumbs-up"></i> UnFollow</a>
		{% else %}
		<a type="submit" id="follow" name="profile_id" value="{{ profile.id }}" class="btn btn-info m-2" style="color:white"><i class="fas fa-thumbs-up" style=""></i> Follow</a>
		{% endif %}
	</form>
{% endif %}
</div>

templates/blog/photo_list.html
{% extends 'album/base.html' %}

{% block javascript %}
  <script>
    $(function () {

      /* SCRIPT TO OPEN THE MODAL WITH THE PREVIEW */
      $("#id_file").change(function () {
        if (this.files && this.files[0]) {
          var reader = new FileReader();
          reader.onload = function (e) {
            $("#image").attr("src", e.target.result);
            $("#modalCrop").modal("show");
          }
          reader.readAsDataURL(this.files[0]);
        }
      });

      /* SCRIPTS TO HANDLE THE CROPPER BOX */
      var $image = $("#image");
      var cropBoxData;
      var canvasData;
      $("#modalCrop").on("shown.bs.modal", function () {
        $image.cropper({
          viewMode: 1,
          aspectRatio: 16/5,
          minCropBoxWidth: 1600,
          minCropBoxHeight: 500,
          ready: function () {
            $image.cropper("setCanvasData", canvasData);
            $image.cropper("setCropBoxData", cropBoxData);
          }
        });
      }).on("hidden.bs.modal", function () {
        cropBoxData = $image.cropper("getCropBoxData");
        canvasData = $image.cropper("getCanvasData");
        $image.cropper("destroy");
      });

      $(".js-zoom-in").click(function () {
        $image.cropper("zoom", 0.1);
      });

      $(".js-zoom-out").click(function () {
        $image.cropper("zoom", -0.1);
      });
      $(".arrow-left").click(function () {
        $image.cropper('move', -1, 0);
      });
      $(".arrow-right").click(function () {
        $image.cropper('move', 1, 0);
      });
      $(".arrow-up").click(function () {
        $image.cropper('move', 0, -1);
      });
      $(".arrow-down").click(function () {
        $image.cropper('move', 0, 1);
      });
      

      /* SCRIPT TO COLLECT THE DATA AND POST TO THE SERVER */
      $(".js-crop-and-upload").click(function () {
        var cropData = $image.cropper("getData");
        $("#id_x").val(cropData["x"]);
        $("#id_y").val(cropData["y"]);
        $("#id_height").val(cropData["height"]);
        $("#id_width").val(cropData["width"]);
        $("#formUpload").submit();
      });

    });
  </script>
{% endblock %}

{% block content %}
<div class="container" style="padding-top: 10px">
  <h2 class="page-header"><strong>Upload a new image or choose from the galley below</strong></h2>

  <h3 class="page-sub-header">Upload a new image</h3>
  <!-- FORM TO UPLOAD THE IMAGES -->
  <form method="post" enctype="multipart/form-data" id="formUpload">
    {% csrf_token %}
    {{ form }}
  </form>

  <!-- MODAL TO CROP THE IMAGE -->
  <div class="modal fade" id="modalCrop">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          <h4 class="modal-title">Crop the photo</h4>
        </div>
        <div class="modal-body">
          <img src="" id="image" style="max-width: 100%;">
        </div>
        <div class="modal-footer">
          <div class="btn-group pull-left" role="group">
            <button type="button" class="btn btn-default js-zoom-in">
              <span class="glyphicon glyphicon-zoom-in"></span>
            </button>
            <button type="button" class="btn btn-default js-zoom-out">
              <span class="glyphicon glyphicon-zoom-out"></span>
            </button>
            <button type="button" class="btn btn-default arrow-left">
              <span class="glyphicon glyphicon-arrow-left"></span>
            </button>
            <button type="button" class="btn btn-default arrow-right">
              <span class="glyphicon glyphicon-arrow-right"></span>
            </button>
            <button type="button" class="btn btn-default arrow-up">
              <span class="glyphicon glyphicon-arrow-up"></span>
            </button>
            <button type="button" class="btn btn-default arrow-down">
              <span class="glyphicon glyphicon-arrow-down"></span>
            </button>
          </div>
          <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
          <button type="button" class="btn btn-primary js-crop-and-upload">Crop and upload</button>
        </div>
      </div>
    </div>
  </div><hr>

<!-- FOR CANCELLING THE OPERATION OR REMOVING THE IMAGE -->
  {% if profile %}
    <div class="section" style="text-align: center;">
      <form method="get">
      <a class="btn btn-primary" href="{{profile.get_absolute_url}}" role="button">Cancel</a>
      <a class="btn btn-danger" href="{% url 'blog:coverRemove' request.user.username request.user.id %}" role="button">Remove</a>
    </form>
    </div><hr>
  {% endif %}

  <!-- CONTAINER TO DISPLAY THE CROPPED IMAGES -->
  <h3 class="">Choose from galley</h3>
  <div class="row" style="margin-top: 20px">
    {% for photo in photos %}
    <div class="col-sm-4 col-md-3 col-12 text-center">
    <form method="get">
      <a href="{% url 'blog:coverUpdate' request.user.username request.user.id photo.id %}">
        <img src="{{ photo.file.url }}" id="{{photo.id}}" href="" class="thumbnail" style="width:100%">
      </a>
    </form>
    <form method="post" action="{% url 'blog:coverDelete' id=photo.id %}">
      {% csrf_token %}
      <button type="submit" class="btn btn-danger btn-sm" onclick="return confirm('Are you sure you want to delete this item?');" style="margin-top: -15px">
        <span class="glyphicon glyphicon-trash"></span> Delete
      </button>
    </form><br>
    </div>
    {% endfor %}
  </div>

</div>
{% endblock %}