blog/urls.py
from django.urls import path
from .import views

app_name='blog'
urlpatterns = [
    path('feed/', views.post_list, name='post_list' ),
    path('auto_search/', views.auto_search, name='auto_search'),
    path('like', views.like_post, name='like_post'),
    path('follow', views.follow, name='follow'),
    path('<int:id>/post-edit', views.post_edit, name='post_edit'),
    path('<int:id>/post-delete', views.post_delete, name="post_delete"),
    path('<int:id>/', views.post_detail, name='post_detail'),
    path('<int:post_id>/comment-delete/<int:id>', views.comment_delete, name="comment_delete"),
    path('<int:reply_id>/reply-delete/<int:post_id>/<int:comment_id>', views.reply_delete, name="reply_delete"),
    path('create-post/', views.post_create, name='create_post'),
    path('login/', views.user_login , name="user_login"),
    path('logout/', views.user_logout , name="user_logout"),
    path('registration/', views.user_registration, name="user_registration"),
    path('edit-profiles/', views.edit_profile, name='edit_profile'),
    path('profile/<str:username>/<int:id>/', views.profile, name='profile'),
    path('cover-photo/', views.photo_list , name="photo_list"),
    path('avatar/', views.avatar_list , name="avatar"),
    path('profile/<str:username>.<int:id>/<int:photo_id>', views.coverUpdate, name="coverUpdate"),
    path('coverRemove/<str:username>.<int:id>', views.coverRemove, name="coverRemove"),
    path('coverDelete/<int:id>/', views.coverDelete, name="coverDelete"),
    path('profile/<str:username>/<int:id>', views.avatarUpdate, name="avatarUpdate"),
    path('avatarRemove/<str:username>/<int:id>', views.avatarRemove, name="avatarRemove"),
    path('avatarDelete/<int:id>', views.avatarDelete, name="avatarDelete"),
    path('settings/<str:username>/', views.settings, name="settings"),
    path('delete/', views.delete_profile, name="delete_profile"),
    path('gallery/<str:username>/', views.gallery, name="galley"),
    path('password_change/', views.change_password, name='change_password'),
    
] 

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static





app_name={'blog','filetype'}
urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('blog.urls', namespace='blog')),
    
    

    # password reset urls
	path('password-reset/', 
		auth_views.PasswordResetView.as_view(template_name='account/password_reset_form.html',email_template_name = 'account/password_reset_email.html'), 
		name="password_reset"),
	path('password-reset/done/', 
		auth_views.PasswordResetDoneView.as_view(template_name='account/password_reset_done.html'), 
		name="password_reset_done"),
	path('password-reset/confirm/<uidb64>/<token>', 
		auth_views.PasswordResetConfirmView.as_view(template_name='account/password_reset_confirm.html',), 
		name="password_reset_confirm"),
	path('password-reset/complete/', 
		auth_views.PasswordResetCompleteView.as_view(template_name='account/password_reset_complete.html'), 
		name="password_reset_complete")
]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

templates/navbar.html
{% load static %}
{% block head_extra %}
{% endblock %}
<body>
  <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-info">
  <!--<a class="navbar-brand " href="{% url 'blog:post_list' %}"><img src="{% static 'images/default/cotton.png' %}" style="width:35px;height:35px"></a>-->
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
   <a class="mx-1" href="{% url 'blog:post_list' %}" style="color: white"><i class="fas fa-home"></i></a>

  <form class="form-inline my-2 my-lg-0 mx-1" action="{% url 'blog:post_list' %}">
    <span><input class="form-control search" type="text" placeholder="Search" aria-label="Search" name="term" id="profile" style="border-radius: 25px;"></span>
    <span><button class="btn btn-info mr-sm-2 btn-sm" type="submit" id="search">
            <i class="fas fa-search" aria-hidden="true"></i>
          </button>
    </span>
  </form>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        
        <!--<a class="nav-link" href="{% url 'blog:create_post' %}"><i class="fas fa-plus"></i></a>-->
      </li>
    </ul>
    
      {% if request.user.is_authenticated %}
        <ul class="navbar-nav">
          <div class="dropdown show my-2">
            <a class="thumbnail p-2" href="{% url 'blog:profile' request.user.username request.user.id %}" style="text-decoration: none;">
            <img class="img-thumbnail rounded-circle p-0" src="{{ request.user.profile.avatar.url }}" alt="" class="navbar-img" style="max-width: 40px"><b style="color:white;"> {{ request.user.first_name|upper }} {{ request.user.last_name|upper }}</b>
          </a>
            <a class="dropdown-toggle" href="#" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="color:white">
            </a>

            <div class="dropdown-menu dropdown-menu-left dropdown-menu-sm-right my-2" aria-labelledby="dropdownMenuLink">
              <a class="dropdown-item" href="{% url 'blog:edit_profile' %}"><small>Edit Profile</small></a>
              <a class="dropdown-item" href="{% url 'blog:settings' request.user.username %}"><small>Settings</small></a>
              <a class="dropdown-item" href="{% url 'blog:user_logout' %}"><small>Logout</small></a>
            </div>
          </div>
        </ul>
      {% endif %}
  </div>
</nav>
</body>